### ISSUE TITLE
Trying to connect with radiolink T8S

### ISSUE THREAD

**Issue by novakorr** [Cleric-K/Universal-RC-Joystick#2]
Hey there!

I've been trying to set my radiolink T8S to connect with my PC and ive been following this guide for a bit. I got an STM32 board and flashed with the correct hex file with an ST-Link i found while trying to buy the bluepill board. After that, I connected my receiver (Radiolink R8FM) to the correct pins, bridged A3 with A4, then plugged in the USB. The board starts lighting up and blinking and cant detect the R8FM. Also the R8FM doesnt light up as well. I confirmed that the receiver is working by connecting it with a UART and binding it with my transmitter (although this way doesnt work bec of something related to SBUS and radiolink using inverted signals or something that I read in your other repo)

any help?

**Comment by Cleric-K** [comment]
Hi, what do you mean by "Also the R8FM doesnt light up as well"?
Are you sure you're powering it up correctly?

**Comment by novakorr** [comment]
the R8FM lights up when its powered. I tried connecting the receiver to a UART to USB bridge to test it out and the LED lights up fine. but when i switch back to the STM32 board, it doesnt light up anymore and the board just blinks.

I also tried connecting the 5V and ground pin to the UART USB bridge but still keeping the SBUS pin on the board's B5 (I am completely new at this and I have no idea what im doing lol) and then plugging both the UART and the board's micro USB thinking that it might be a power issue. I was thinking that if its a power issue, I can power it using the 5V from the UART and keep the B5 data connection from the board, which is powered by its own micro USB. Unfortunately that only results in both the receiver and the board lighting up, but the board is still blinking

**Comment by Cleric-K** [comment]
> I tried connecting the receiver to a UART to USB bridge to test it out and the LED lights up fine. but when i switch back to the STM32 board, it doesnt light up anymore

I'm not sure of which LED you speak here. Is there LED on the R8FM? Does it show if there's connection with the transmitter?

**Comment by novakorr** [comment]
Hey,

So you were right about the power issue. I decided to resolder everything and somehow everything works. Thanks!

**Comment by Cleric-K** [comment]
OK, Great!
