### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by elnenez** [Cleric-K/Universal-RC-Joystick#4]
Hello,

I am trying to build the project using PlatformIO but it fails with the following error:

C:\Users\m.platformio\packages\framework-stm32cubef1\Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_iwdg.c:124:83: error: 'LSI_STARTUP_TIME' undeclared

Any help? Thank you.

The complete log is next:

Processing genericSTM32F103CB (platform: ststm32; board: genericSTM32F103CB; framework: stm32cube)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103CB.html
PLATFORM: ST STM32 (17.4.0) > STM32F103CB (20k RAM. 128k Flash)        
HARDWARE: STM32F103CBT6 72MHz, 20KB RAM, 128KB Flash
DEBUG: Current (stlink) External (blackmagic, cmsis-dap, jlink, stlink)
PACKAGES:
 - framework-stm32cubef1 @ 1.8.4
 - tool-ldscripts-ststm32 @ 0.2.0
 - toolchain-gccarmnoneeabi @ 1.70201.0 (7.2.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 28 compatible libraries
Scanning dependencies...
Dependency Graph
|-- STM32_USB_Device_Library-Core
|-- STM32_USB_Device_Library-CustomHID
Building in release mode
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_adc.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_adc_ex.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_can.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_cec.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_cortex.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_crc.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_dac.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_dac_ex.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_dma.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_eth.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_exti.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_flash.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_flash_ex.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_gpio.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_gpio_ex.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_hcd.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_i2c.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_i2s.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_irda.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_iwdg.o
C:\Users\m\.platformio\packages\framework-stm32cubef1\Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_iwdg.c: In function 'HAL_IWDG_Init':
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_mmc.o
C:\Users\m\.platformio\packages\framework-stm32cubef1\Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_iwdg.c:124:83: error: 'LSI_STARTUP_TIME' undeclared (first use in this 
function); did you mean 'LSE_STARTUP_TIMEOUT'?
 #define HAL_IWDG_DEFAULT_TIMEOUT        (((6UL * 256UL * 1000UL) / LSI_VALUE) + ((LSI_STARTUP_TIME / 1000UL) + 1UL))
                                                                                   ^
C:\Users\m\.platformio\packages\framework-stm32cubef1\Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_iwdg.c:196:39: note: in expansion of macro 'HAL_IWDG_DEFAULT_TIMEOUT'  
     if ((HAL_GetTick() - tickstart) > HAL_IWDG_DEFAULT_TIMEOUT)
                                       ^~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\m\.platformio\packages\framework-stm32cubef1\Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_iwdg.c:124:83: note: each undeclared identifier is reported only once for each function it appears in
 #define HAL_IWDG_DEFAULT_TIMEOUT        (((6UL * 256UL * 1000UL) / LSI_VALUE) + ((LSI_STARTUP_TIME / 1000UL) + 1UL))
                                                                                   ^
C:\Users\m\.platformio\packages\framework-stm32cubef1\Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_iwdg.c:196:39: note: in expansion of macro 'HAL_IWDG_DEFAULT_TIMEOUT'  
     if ((HAL_GetTick() - tickstart) > HAL_IWDG_DEFAULT_TIMEOUT)
                                       ^~~~~~~~~~~~~~~~~~~~~~~~
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_nand.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_nor.o
Compiling .pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_pccard.o
*** [.pio\build\genericSTM32F103CB\FrameworkHALDriver\Src\stm32f1xx_hal_iwdg.o] Error 1
======================================================================== [FAILED] Took 7.37 seconds ========================================================================

**Comment by Cleric-K** [comment]
Hi, I suppose that some of the framework components in PlatformIO have been upgraded and now they are out of sync with the codebase of the project generated by STMCube. Probably the project files will need to be regenerated/updated through an updated Cube. I'm only guessing. I'll have a chance to check only later this week.

May I ask about the reason for building it yourself? Did you add some new features?

**Comment by elnenez** [comment]
Ok, thanks. I think that is the problem. The project generated by STMCube used firmware 1.6.1 and PlatformIO uses 1.8.4.
I would like to customize the number of axis and buttons in the joystick.

**Comment by Cleric-K** [comment]
Hi, I migrated the project to the newer version. You can checkout from this branch
https://github.com/Cleric-K/Universal-RC-Joystick/tree/newstmcube
However I haven't tested anything. I only saw that it builds. There a lot of changes compared to the old stmcube so it's very likely that something is broken. Try first to build and upload without any modifications. If it works OK, then you can go on with modifying.

**Comment by elnenez** [comment]
Hi, I have tested the C8 version without any modifications and it works OK.
Thanks!
